Serializable instance
nutgram/nutgram pull request #172
Opened 2022-07-14 12:29 UTC by SergiX44

2022-07-19 09:42 UTC, Lukasss93 approved these changes

2022-07-19 17:04 UTC, Lukasss93 requested changes
nope

![immagine](https://user-images.githubusercontent.com/4071613/179808373-fc9591ed-476e-40be-a438-f86f707ddea0.png)

2022-07-19 19:19 UTC, SergiX44 commented
![giphy](https://user-images.githubusercontent.com/4172890/179831251-d63676cf-a7fe-48be-9fce-6c3b16951788.gif)

2022-07-21 16:02 UTC, Lukasss93 approved these changes

2022-07-21 21:11 UTC, merged