support bot_id cache
nutgram/nutgram pull request #184
Opened 2022-07-31 20:21 UTC by SergiX44

2022-07-31 20:49 UTC, Lukasss93 commented
With "getMe" method you can get automatically (?) the current bot id
https://core.telegram.org/bots/api#getme

Example:
![immagine](https://user-images.githubusercontent.com/4071613/182044811-8e1851b1-aa3f-4760-85ee-aa40c64d36af.png)


Can it be useful?

2022-07-31 21:07 UTC, SergiX44 commented
No, I don't like it that much.
It means an API call every time you have to instantiate the bot. Since this is something that 99.8% of users will not encounter, I wouldn't add that overhead.

2022-07-31 21:56 UTC, Lukasss93 requested changes

2022-08-01 05:39 UTC, flakka2022 commented
> With "getMe" method you can get automatically (?) the current bot id https://core.telegram.org/bots/api#getme
> 
> Example: ![immagine](https://user-images.githubusercontent.com/4071613/182044811-8e1851b1-aa3f-4760-85ee-aa40c64d36af.png)
> 
> Can it be useful?

first part of every token is the bot id .

2022-08-01 08:57 UTC, Lukasss93 approved these changes

2022-08-01 09:44 UTC, flakka2022 approved these changes

2022-08-01 10:15 UTC, Lukasss93 approved these changes

2022-08-01 10:16 UTC, merged