Logging
nutgram/nutgram pull request #196
Opened 2022-09-10 16:40 UTC by Lukasss93

2022-09-10 21:25 UTC, SergiX44 requested changes

2022-09-10 21:25 UTC, SergiX44 commented on laravel/config.php
> +    'log_channel' => env('TELEGRAM_LOG_CHANNEL', 'null'),
why null as string?

2022-09-10 21:29 UTC, Lukasss93 commented on laravel/config.php
> +    'log_channel' => env('TELEGRAM_LOG_CHANNEL', 'null'),
it's a channel name

2022-09-14 20:30 UTC, SergiX44 approved these changes

2022-09-14 20:30 UTC, merged